export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'

export const SORT_USERS = 'SORT_USERS'
export const UPDATE_USER_PAGE = 'UPDATE_PAGE'
export const UPDATE_USER_ROWS = 'UPDATE_ROWS'