export const ADD_PROJECT_JURISDICTION_REQUEST = 'ADD_PROJECT_JURISDICTION_REQUEST'
export const ADD_PROJECT_JURISDICTION_SUCCESS = 'ADD_PROJECT_JURISDICTION_SUCCESS'

export const UPDATE_PROJECT_JURISDICTION_REQUEST = 'UPDATE_PROJECT_JURISDICTION_REQUEST'
export const UPDATE_PROJECT_JURISDICTION_SUCCESS = 'UPDATE_PROJECT_JURISDICTION_SUCCESS'

export const GET_PROJECT_JURISDICTIONS_REQUEST = 'GET_PROJECT_JURISDICTIONS_REQUEST'
export const GET_PROJECT_JURISDICTIONS_SUCCESS = 'GET_PROJECT_JURISDICTIONS_SUCCESS'

export const CLEAR_JURISDICTIONS = 'CLEAR_JURISDICTIONS'