export const ADD_USER_REQUEST = 'ADD_USER_REQUEST'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'

export const ADD_USER_PICTURE_REQUEST = 'ADD_USER_PICTURE_REQUEST'
export const ADD_USER_PICTURE_SUCCESS = 'ADD_USER_PICTURE_SUCCESS'