export const ADD_USER_REQUEST = 'ADD_USER_REQUEST'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'
export const UPDATE_CURRENT_USER_AVATAR = 'UPDATE_CURRENT_USER_AVATAR'
export const REMOVE_CURRENT_USER_AVATAR = 'REMOVE_CURRENT_USER_AVATAR'

export const ADD_USER_IMAGE_REQUEST = 'ADD_USER_IMAGE_REQUEST'
export const ADD_USER_IMAGE_SUCCESS = 'ADD_USER_IMAGE_SUCCESS'

export const GET_USER_IMAGE_REQUEST = 'GET_USER_IMAGE_REQUEST'
export const GET_USER_IMAGE_SUCCESS = 'GET_USER_IMAGE_SUCCESS'

export const DELETE_USER_IMAGE_REQUEST = 'DELETE_USER_IMAGE_REQUEST'
export const DELETE_USER_IMAGE_SUCCESS = 'DELETE_USER_IMAGE_SUCCESS'

export const ON_CLOSE_ADD_EDIT_USER = 'ON_CLOSE_ADD_EDIT_USER'

export const LOAD_ADD_EDIT_AVATAR = 'LOAD_ADD_EDIT_AVATAR'