before_script:
  - docker info
  - yarn -version
  - npm -version
  - node -v

variables:
  VERSION: 0.6.0
  SUB_BUILD: $CI_PIPELINE_ID
  BRANCH: $CI_COMMIT_REF_NAME

stages:
  - build
  - test
  - push

esquire_frontend_build:
  stage: build
  tags:
    - iiu
  script:
    - yarn build:image:dev

esquire_frontend_test_image:
  stage: test
  script:
    - docker-compose -f docker-compose.dev.yml run --user=988 dev npm run test:local
  tags:
    - iiu
    


esquire_frontend_push_image::
  stage: push
  script:
    - yarn build:image:prod
    - curl -fsSL https://git.phiresearchlab.org/snippets/10/raw | bash
#  only:
#    - master
  environment:
    name: DTR Frontend
    url: https://dtr.phiresearchlab.org/repositories/iiu/esquire-frontend/tags
  tags:
    - iiu

esquire_frontend_deploy_test::
  stage: push
  script:
    - yarn build:image:prod
    - curl -fsSL https://git.phiresearchlab.org/snippets/10/raw | bash
#  only:
#    - master
  environment:
    name: Azure Test
    url: https://esquiretest.phiresearchlab.org
  when: manual
  only: 
    - test
  tags:
    - iiu