#before_script:

variables:
  VERSION: 0.6.0
  SUB_BUILD: $CI_PIPELINE_ID
  BRANCH: $CI_COMMIT_REF_NAME

stages:
  - lint
  - test
  - build
  - deploy

lint_frontend:
  stage: lint
  script:
    - npm install
    - npm run lint
  tags:
    - phlip2-fe

test_frontend:
  stage: test
  script:
    - npm install
    - npm run test:local
  tags:
    - phlip2-fe

build_frontend_dev_internal:
  stage: build
  script:
    - npm install
    - cp ~iiu-deploy/.env.fe ./
    - npm run build
    - cp -r ./dist ~iiu-deploy/esquire-frontend/
    - cp -r ./scripts ~iiu-deploy/esquire-frontend/
    - cp ./package.json ~iiu-deploy/esquire-frontend/
  tags:
    - phlip2-fe
  environment:
    name: Internal PHLIP2 Dev
    url: http://lvscent7064.lab.local

deploy_frontend_dev_internal:
  stage: deploy
  script:
    - npm install --production
    - sudo pm2 stop frontend
    - sudo pm2 start scripts/serve.js --name frontend
  tags:
    - phlip2-fe
  environment:
    name: Internal PHLIP2 Dev
    url: http://lvscent7064.lab.local

build_frontend_dev_azure:
  stage: build
  script:
    - npm install
    - cp ~iiu-deploy/configs/.env ./
    - npm run build
    - cp -r ./dist ~iiu-deploy/esquire-frontend/
    - cp -r ./scripts ~iiu-deploy/esquire-frontend/
    - cp ./package.json ~iiu-deploy/esquire-frontend/
  tags:
    - azure-phlipdev-fe
  when: manual
  environment:
    name: Azure PHLIP2 Dev
    url: https://phlip2dev.phiresearchlab.org

deploy_frontend_dev_azure:
  stage: deploy
  script:
    - npm install --production
    - sudo pm2 stop frontend
    - sudo pm2 start scripts/serve.js --name frontend
  when: manual
  tags:
    - azure-phlipdev-fe
  environment:
    name: Azure PHLIP2 Dev
    url: https://phlip2dev.phiresearchlab.org

#build_esquire_frontend:
#  stage: build
#  tags:
#    - iiu
#  script:
#    - npm -version
#    - node -v
#    - yarn build:image:dev
#
#test_esquire_frontend_image:
#  stage: test
#  tags:
#    - iiu
#  script:
#    - docker-compose -f docker-compose.dev.yml run --user=988 app npm run test:local
#    - docker-compose -f docker-compose.dev.yml down
#
#push_esquire_frontend_image:
#  stage: push
#  script:
#    - yarn build:image:prod
#    - curl -fsSL https://git.phiresearchlab.org/snippets/10/raw | bash
#  environment:
#    name: DTR Frontend
#    url: https://dtr.phiresearchlab.org/repositories/iiu/esquire-frontend/tags
#  tags:
#    - iiu

#deploy_local_test_esquire_frontend:
#  stage: push
#  script:
#    - npm install
#    - npm run build
#    - echo "APP_API_URL=$TEST_APP_API_URL">.env
#    - pm2 stop serve
#    - pm2 start scripts/serve.js
#  environment:
#    name: IIU Esquire Test
#    url: https://esquiretest.phiresearchlab.org
#  when: manual
#  only:
#    - test
#  tags:
#    - iiu
#
#deploy_test_esquire_frontend:
#  stage: push
#  script:
#    - npm install
#    - npm run build
#    - echo "APP_API_URL=$TEST_APP_API_URL">.env
#    - pm2 stop serve
#    - pm2 start scripts/serve.js
#  environment:
#    name: Azure Test
#    url: https://phliptest.phiresearchlab.org
#  when: manual
#  # only:
#  #   - test
#  tags:
#    - azure-esquire
#
#deploy_stage_esquire_frontend:
#  stage: push
#  script:
#    - npm install
#    - npm run build
#    - echo "APP_API_URL=$TEST_APP_API_URL">.env
#    - pm2 stop serve
#    - pm2 start scripts/serve.js
#  environment:
#    name: Azure Stage
#    url: https://phlipstage.phiresearchlab.org
#  when: manual
#  only:
#    - stage
#  tags:
#   - azure-esquire