variables:
  SUB_BUILD: $CI_PIPELINE_ID
  BRANCH: $CI_COMMIT_REF_NAME

stages:
  - lint
  - unit test
  - staging
  - e2e test
  - build
  - deploy

lint:
  stage: lint
  script:
    - npm install
    - npm run lint
  tags:
    - phlip2-dev
  only:
    - development
    - test
    - e2e-cicd
  cache:
    key: "$CI_BUILD_REF_NAME"
    untracked: true
    paths:
      - node_modules/
      - .env
  environment:
    name: Internal PHLIP2 Dev
    url: http://lvscent7064.lab.local

test:
  stage: unit test
  script:
    - npm run test:local
  tags:
    - phlip2-dev
  only:
    - development
    - test
    - e2e-cicd
  cache:
    key: "$CI_BUILD_REF_NAME"
    untracked: true
    paths:
      - node_modules/
      - .env
  environment:
    name: Internal PHLIP2 Dev
    url: http://lvscent7064.lab.local

build and deploy on staging:
  stage: staging
  before_script:
    - if pm2 list | grep fe; then pm2 stop fe; else echo "no fe process running"; fi
  script:
    - echo "APP_DOC_MANAGE_API=http://0.0.0.0:3000" > .env
    - echo "APP_API_URL=http://0.0.0.0:8000" >> .env
    - echo "HEADLESS=1" >> .env
    - pm2 start scripts/start.js --name fe
  tags:
    - phlip2-dev
  only:
    - e2e-cicd
  cache:
    key: "$CI_BUILD_REF_NAME"
    untracked: true
    paths:
      - node_modules/
      - .env
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 week
  environment:
    name: Internal PHLIP2 Dev
    url: http://lvscent7064.lab.local

run e2e tests staging:
  stage: e2e test
  script:
    - npm run test:e2e
  tags:
    - phlip2-dev
  only:
    - e2e-cicd
  cache:
    key: "$CI_BUILD_REF_NAME"
    untracked: true
    paths:
      - node_modules/
      - .env
  environment:
    name: Internal PHLIP2 Dev
    url: http://lvscent7064.lab.local
  dependencies:
    - build and deploy on staging

build dev azure:
  stage: build
  script:
    - npm install
    - cat ~iiu-deploy/config/.env.fe >> .env
    - npm run build
    - cp -r ./dist ~iiu-deploy/esquire-frontend-deploy/
    - cp -r ./scripts ~iiu-deploy/esquire-frontend-deploy/
    - cp -r ./config ~iiu-deploy/esquire-frontend-deploy/
    - cp ./package.json ~iiu-deploy/esquire-frontend-deploy/
    - cp .env ~iiu-deploy/esquire-frontend-deploy/
  tags:
    - az-phlip2dev-fe
  when: manual
  allow_failure: false
  only:
    - development
  environment:
    name: Azure PHLIP2 Dev
    url: https://phlip2dev.phiresearchlab.org
  dependencies: []

deploy dev azure:
  stage: deploy
  script:
    - cd ~iiu-deploy/esquire-frontend-deploy
    - npm install --production
    - if pm2 list | grep phlip-fe; then pm2 stop phlip-fe; else echo "no phlip-fe process running"; fi
    - pm2 start scripts/serve.js --name phlip-fe
  tags:
    - az-phlip2dev-fe
  environment:
    name: Azure PHLIP2 Dev
    url: https://phlip2dev.phiresearchlab.org
  only:
    - development
  dependencies: []

build test azure:
  stage: build
  script:
    - npm install
    - cat ~iiu-deploy/config/.env.fe >> .env
    - npm run build
    - cp -r ./dist ~iiu-deploy/esquire-frontend-deploy/
    - cp -r ./scripts ~iiu-deploy/esquire-frontend-deploy/
    - cp -r ./config ~iiu-deploy/esquire-frontend-deploy/
    - cp ./package.json ~iiu-deploy/esquire-frontend-deploy/
    - cp .env ~iiu-deploy/esquire-frontend-deploy/
  tags:
    - az-phlip2test-fe
  when: manual
  allow_failure: false
  only:
    - test
  environment:
    name: Azure PHLIP2 Test
    url: https://phlip2test.phiresearchlab.org

deploy test azure:
  stage: deploy
  script:
    - cd ~iiu-deploy/esquire-frontend-deploy
    - npm install --production
    - if pm2 list | grep phlip-fe; then pm2 stop phlip-fe; else echo "no phlip-fe process running"; fi
    - pm2 start scripts/serve --name phlip-fe
  tags:
    - az-phlip2test-fe
  only:
    - test
  environment:
    name: Azure PHLIP2 Test
    url: https://phlip2test.phiresearchlab.org