#before_script:

variables:
  VERSION: 0.6.0
  SUB_BUILD: $CI_PIPELINE_ID
  BRANCH: $CI_COMMIT_REF_NAME

stages:
  - lint
  - test
  - build
  - deploy

lint_frontend:
  stage: lint
  script:
    - npm install
    - npm run lint
  tags:
    - phlip2-dev

test_frontend:
  stage: test
  script:
    - npm install
    - npm run test:local
  tags:
    - phlip2-dev

build_dev_internal:
  stage: build
  script:
    - npm install
    - cat ~iiu-deploy/config/.env.fe >> .env
    - npm run build
    - cp -r ./dist ~iiu-deploy/esquire-frontend-deploy/
    - cp -r ./scripts ~iiu-deploy/esquire-frontend-deploy/
    - cp -r ./config ~iiu-deploy/esquire-frontend-deploy/
    - cp ./package.json ~iiu-deploy/esquire-frontend-deploy/
    - cp .env ~iiu-deploy/esquire-frontend-deploy/
  allow_failure: false
  when: manual
  tags:
    - phlip2-dev
  environment:
    name: Internal PHLIP2 Dev
    url: http://lvscent7064.lab.local

deploy_dev_internal:
  stage: deploy
  script:
    - cd ~iiu-deploy/esquire-frontend-deploy
    - npm install --production
    - pm2 stop phlip-fe
    - pm2 start scripts/serve.js --name phlip-fe
  tags:
    - phlip2-dev
  environment:
    name: Internal PHLIP2 Dev
    url: http://lvscent7064.lab.local

build_dev_azure:
  stage: build
  script:
    - npm install
    - cat ~iiu-deploy/config/.env.fe >> .env
    - npm run build
    - cp -r ./dist ~iiu-deploy/esquire-frontend-deploy/
    - cp -r ./scripts ~iiu-deploy/esquire-frontend-deploy/
    - cp -r ./config ~iiu-deploy/esquire-frontend-deploy/
    - cp ./package.json ~iiu-deploy/esquire-frontend-deploy/
    - cp .env ~iiu-deploy/esquire-frontend-deploy/
  tags:
    - az-phlip2dev-fe
  when: manual
  allow_failure: false
  environment:
    name: Azure PHLIP2 Dev
    url: https://phlip2dev.phiresearchlab.org

deploy_dev_azure:
  stage: deploy
  script:
    - whoami
    - cd ~iiu-deploy/esquire-frontend-deploy
    - npm install --production
    - pm2 stop phlip-fe
    - pm2 start scripts/serve.js --name phlip-fe
  tags:
    - az-phlip2dev-fe
  environment:
    name: Azure PHLIP2 Dev
    url: https://phlip2dev.phiresearchlab.org

#build_test_azure:
#  stage: build
#  script:
#    - npm install
#    - cat ~iiu-deploy/config/.env.fe >> .env
#    - npm run build
#    - cp -r ./dist ~iiu-deploy/esquire-frontend-deploy/
#    - cp -r ./scripts ~iiu-deploy/esquire-frontend-deploy/
#    - cp -r ./config ~iiu-deploy/esquire-frontend-deploy/
#    - cp ./package.json ~iiu-deploy/esquire-frontend-deploy/
#    - cp .env ~iiu-deploy/esquire-frontend-deploy/
#  tags:
#    - az-phlip2test-fe
#  when: manual
#  allow_failure: false
#  environment:
#    name: Azure PHLIP2 Test
#    url: https://phlip2test.phiresearchlab.org
#
#deploy_test_azure:
#  stage: deploy
#  script:
#    - whoami
#    - cd ~iiu-deploy/esquire-frontend-deploy
#    - npm install --production
#    - pm2 stop phlip-fe
#    - pm2 start scripts/serve.js --name phlip-fe
#  tags:
#    - az-phlip2test-fe
#  environment:
#    name: Azure PHLIP2 Test
#    url: https://phlip2test.phiresearchlab.org