before_script:
  - docker info
  - yarn -version
  - npm -version
  - node -v

variables:
  VERSION: 0.4.0
  SUB_BUILD: $CI_PIPELINE_ID

stages:
  - build
  - test
  - push

esquire_frontend_build:
  stage: build
  tags:
    - iiu
  script:
    - yarn build:image:dev

esquire_frontend_test_image:
  stage: test
  script:
    - docker-compose -f docker-compose.dev.yml run --user=988 dev npm run test:local
  tags:
    - iiu
    


esquire_frontend_push_image::
  stage: push
  script:
    - yarn build:image:prod
    - curl -fsSL https://git.phiresearchlab.org/snippets/9/raw | bash
#  only:
#    - master
  tags:
    - iiu
