before_script:
  - docker info
  - yarn -version
  - npm -version
  - node -v

variables:
  MAIN_VERSION: "0"
  SUB_VERSION: "1"
  SUB_BUILD: $CI_PIPELINE_ID

stages:
  - build
  - test
  #- push

esquire_frontend_build:
  stage: build
  tags:
    - iiu
  script:
    - yarn build:image:dev

esquire_frontend_test_image:
  stage: test
  script:
    - yarn test
  tags:
    - iiu
    


#esquire_frontend_push_image::
#  stage: push
#  script:
#    - curl -fsSL https://git.phiresearchlab.org/snippets/2/raw | bash
#  only:
#    - master
#  tags:
#    - iiu
