version: "3.2"
services:
  app:
    container_name: esquire-frontend-dev
    image: esquire-frontend:dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules/
      - .:/usr/src/app
    ports:
      - ${APP_PORT:-5200}:${APP_PORT:-5200}