FROM node:8.4.0

ENV NPM_CONFIG_LOGLEVEL warn
SHELL ["/bin/bash", "-c"]

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .

RUN npm dedupe
RUN npm install --no-optional
RUN npm run build
RUN npm prune

CMD npm run serve:local

EXPOSE 5000
