version: "3.2"
services:
  app:
    container_name: esquire-frontend-prod
    image: esquire-frontend:prod
    build:
      context: .
      dockerfile: Dockerfile-prod
      args:
        - APP_API_URL
        - APP_DOC_MANAGE_API
        - APP_LOG_REQUESTS
        - APP_IS_HTTPS
        - APP_SAML_REQUEST_URL
        - APP_IS_SAML_ENABLED
    env_file:
      - .env
    ports:
      - ${APP_PORT:-5000}:${APP_PORT:-5000}