version: "3.2"
services:
  dev:
    container_name: esquire-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    image: esquire-frontend:dev
    ports:
      - ${APP_PORT:-5200}:${APP_PORT:-5200}
    volumes:
      - /usr/src/app/node_modules/
      - .:/usr/src/app