FROM node:8.7.0

ENV NPM_CONFIG_LOGLEVEL error
SHELL ["/bin/bash", "-c"]

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .

RUN npm install --no-optional
RUN npm run build
RUN npm install --production --no-optional
RUN npm dedupe

CMD npm run serve:local