version: "3.2"
services:
  dev:
    container_name: esquire-frontend-dev-v1
    build:
      context: .
      dockerfile: Dockerfile
    image: esquire-frontend:dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - /usr/src/app/node_modules/
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
