export const GET_SCHEME_REQUEST = 'GET_SCHEME_REQUEST'
export const GET_SCHEME_SUCCESS = 'GET_SCHEME_SUCCESS'
export const GET_SCHEME_FAIL = 'GET_SCHEME_FAIL'

export const REORDER_SCHEME_REQUEST = 'REORDER_SCHEME_REQUEST'
export const REORDER_SCHEME_SUCCESS = 'REORDER_SCHEME_SUCCESS'
export const REORDER_SCHEME_FAIL = 'REORDER_SCHEME_FAIL'

export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS'
export const ADD_QUESTION_REQUEST = 'ADD_QUESTION_REQUEST'
export const ADD_QUESTION_FAIL = 'ADD_QUESTION_FAIL'

export const ADD_CHILD_QUESTION_REQUEST = 'ADD_CHILD_QUESTION_REQUEST'
export const ADD_CHILD_QUESTION_SUCCESS = 'ADD_CHILD_QUESTION_SUCCESS'
export const ADD_CHILD_QUESTION_FAIL = 'ADD_CHILD_QUESTION_FAIL'

export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS'
export const UPDATE_QUESTION_REQUEST = 'UPDATE_QUESTION_REQUEST'
export const UPDATE_QUESTION_FAIL = 'UPDATE_QUESTION_FAIL'

export const LOCK_SCHEME_REQUEST = 'LOCK_SCHEME_REQUEST'
export const LOCK_SCHEME_SUCCESS = 'LOCK_SCHEME_SUCCESS'
export const LOCK_SCHEME_FAIL = 'LOCK_SCHEME_FAIL'

export const UNLOCK_SCHEME_REQUEST = 'UNLOCK_SCHEME_REQUEST'
export const UNLOCK_SCHEME_SUCCESS = 'UNLOCK_SCHEME_SUCCESS'
export const UNLOCK_SCHEME_FAIL = 'UNLOCK_SCHEME_FAIL'

export const HANDLE_QUESTION_TREE_CHANGE = 'HANDLE_QUESTION_TREE_CHANGE'
export const TOGGLE_HOVER = 'TOGGLE_HOVER'
export const ENABLE_HOVER = 'ENABLE_HOVER'
export const DISABLE_HOVER = 'DISABLE_HOVER'

export const UPDATE_TYPE = 'UPDATE_TYPE'
export const CLEAR_STATE = 'CLEAR_STATE'
export const SET_EMPTY_STATE = 'SET_EMPTY_STATE'
export const RESET_ALERT_ERROR = 'RESET_REORDER_ERROR'