export const GET_SCHEME_REQUEST = 'GET_SCHEME_REQUEST'
export const GET_SCHEME_SUCCESS = 'GET_SCHEME_SUCCESS'

export const HANDLE_QUESTION_TREE_CHANGE = 'HANDLE_QUESTION_TREE_CHANGE'
export const TOGGLE_HOVER = 'TOGGLE_HOVER'

export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS'
export const ADD_QUESTION_REQUEST = 'ADD_QUESTION_REQUEST'
export const ADD_QUESTIONS_FAIL = 'ADD_QUESTIONS_FAIL'