export const GET_SCHEME_REQUEST = 'GET_SCHEME_REQUEST'
export const GET_SCHEME_SUCCESS = 'GET_SCHEME_SUCCESS'
export const REORDER_SCHEME_REQUEST = 'REORDER_SCHEME_REQUEST'

export const HANDLE_QUESTION_TREE_CHANGE = 'HANDLE_QUESTION_TREE_CHANGE'
export const TOGGLE_HOVER = 'TOGGLE_HOVER'
export const ENABLE_HOVER = 'ENABLE_HOVER'
export const DISABLE_HOVER = 'DISABLE_HOVER'

export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS'
export const ADD_QUESTION_REQUEST = 'ADD_QUESTION_REQUEST'
export const ADD_QUESTION_FAIL = 'ADD_QUESTION_FAIL'

export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS'
export const UPDATE_QUESTION_REQUEST = 'UPDATE_QUESTION_REQUEST'
export const UPDATE_QUESTION_FAIL = 'UPDATE_QUESTION_FAIL'

export const UPDATE_TYPE = 'UPDATE_TYPE'