export const GET_QUESTION_REQUEST = 'GET_QUESTION_REQUEST'
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS'
export const GET_QUESTION_FAIL = 'GET_QUESTION_FAIL'

export const GET_CODING_OUTLINE_REQUEST = 'GET_CODING_OUTLINE_REQUEST'
export const GET_CODING_OUTLINE_SUCCESS = 'GET_CODING_OUTLINE_SUCCESS'
export const GET_CODING_OUTLINE_FAIL = 'GET_CODING_OUTLINE_FAIL'