export const GET_QUESTION_REQUEST = 'GET_QUESTION_REQUEST'
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS'
export const GET_QUESTION_FAIL = 'GET_QUESTION_FAIL'

export const GET_CODING_OUTLINE_REQUEST = 'GET_CODING_OUTLINE_REQUEST'
export const GET_CODING_OUTLINE_SUCCESS = 'GET_CODING_OUTLINE_SUCCESS'
export const GET_CODING_OUTLINE_FAIL = 'GET_CODING_OUTLINE_FAIL'

export const ANSWER_QUESTION_REQUEST = 'ANSWER_QUESTION_REQUEST'
export const ANSWER_QUESTION_SUCCESS = 'ANSWER_QUESTION_SUCCESS'
export const ANSWER_QUESTION_FAIL = 'ANSWER_QUESTION_FAIL'

export const ON_CHANGE_COMMENT = 'ON_CHANGE_COMMENT'
export const ON_CHANGE_PINCITE = 'ON_ADD_PINCITE'