export const GET_QUESTION_REQUEST = 'GET_QUESTION_REQUEST'
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS'
export const GET_QUESTION_FAIL = 'GET_QUESTION_FAIL'

export const GET_NEXT_QUESTION = 'GET_NEXT_QUESTION'
export const GET_PREV_QUESTION = 'GET_PREV_QUESTION'

export const GET_CODING_OUTLINE_REQUEST = 'GET_CODING_OUTLINE_REQUEST'
export const GET_CODING_OUTLINE_SUCCESS = 'GET_CODING_OUTLINE_SUCCESS'
export const GET_CODING_OUTLINE_FAIL = 'GET_CODING_OUTLINE_FAIL'

export const UPDATE_USER_ANSWER_REQUEST = 'UPDATE_USER_ANSWER_REQUEST'
export const UPDATE_USER_ANSWER_SUCCESS = 'UPDATE_USER_ANSWER_SUCCESS'
export const UPDATE_USER_ANSWER_FAIL = 'UPDATE_USER_ANSWER_FAIL'

export const ON_CHANGE_COMMENT = 'ON_CHANGE_COMMENT'
export const ON_CHANGE_PINCITE = 'ON_ADD_PINCITE'

export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES'
export const ON_CHANGE_CATEGORY = 'ON_CHANGE_CATEGORY'

export const ON_CLEAR_ANSWER = 'ON_CLEAR_ANSWER'