export const GET_VALIDATION_OUTLINE_REQUEST = 'GET_VALIDATION_OUTLINE_REQUEST'
export const GET_VALIDATION_OUTLINE_SUCCESS = 'GET_VALIDATION_OUTLINE_SUCCESS'
export const GET_VALIDATION_OUTLINE_FAIL = 'GET_VALIDATION_OUTLINE_FAIL'

export const SAVE_USER_ANSWER_REQUEST = 'SAVE_USER_ANSWER_REQUEST_VALIDATION'
export const SAVE_USER_ANSWER_FAIL = 'SAVE_USER_ANSWER_FAIL_VALIDATION'
export const SAVE_USER_ANSWER_SUCCESS = 'SAVE_USER_ANSWER_SUCCESS_VALIDATION'
export const UPDATE_USER_ANSWER = 'UPDATE_USER_ANSWER_VALIDATION'
//export const GET_CODED_USERS_LIST_REQUEST = 'GET_CODED_USERS_LIST_REQUEST'

export const GET_USER_VALIDATED_QUESTIONS_REQUEST = 'GET_USER_VALIDATED_QUESTIONS_REQUEST'
export const GET_USER_VALIDATED_QUESTIONS_SUCCESS = 'GET_USER_VALIDATED_QUESTIONS_SUCCESS'
export const GET_USER_VALIDATED_QUESTIONS_FAIL = 'GET_USER_VALIDATED_QUESTIONS_FAIL'

export const CLEAR_FLAG = 'CLEAR_FLAG'
export const CLEAR_RED_FLAG = 'CLEAR_RED_FLAG'
export const CLEAR_FLAG_SUCCESS = 'CLEAR_FLAG_SUCCESS'
export const CLEAR_FLAG_FAIL = 'CLEAR_FLAG_FAIL'

export const ON_QUESTION_SELECTED_IN_NAV = 'ON_QUESTION_SELECTED_IN_NAV_VALIDATION'
export const GET_NEXT_QUESTION = 'GET_NEXT_QUESTION_VALIDATION'
export const GET_PREV_QUESTION = 'GET_PREV_QUESTION_VALIDATION'
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS_VALIDATION'
export const GET_QUESTION_FAIL = 'GET_QUESTION_FAIL_VALIDATION'

export const ON_CHANGE_COMMENT = 'ON_CHANGE_COMMENT_VALIDATION'
export const ON_CHANGE_PINCITE = 'ON_CHANGE_PINCITE_VALIDATION'
export const ON_CHANGE_CATEGORY = 'ON_CHANGE_CATEGORY_VALIDATION'

export const ON_CLEAR_ANSWER = 'ON_CLEAR_ANSWER_VALIDATION'
export const ON_CLOSE_SCREEN = 'ON_CLOSE_SCREEN_VALIDATION'
export const ON_CHANGE_JURISDICTION = 'ON_CHANGE_JURISDICTION_VALIDATION'
export const ON_APPLY_ANSWER_TO_ALL = 'ON_APPLY_ANSWER_TO_ALL_VALIDATION'
export const UPDATE_EDITED_FIELDS = 'UPDATE_EDITED_FIELDS_VALIDATION'

export const DISMISS_API_ALERT = 'DISMISS_API_ALERT_VALIDATION'

export const ADD_REQUEST_TO_QUEUE = 'ADD_REQUEST_TO_QUEUE_VALIDATION'
export const REMOVE_REQUEST_FROM_QUEUE = 'REMOVE_REQUEST_FROM_QUEUE_VALIDATION'
export const SEND_QUEUE_REQUESTS = 'SEND_QUEUE_REQUESTS_VALIDATION'