export const GET_VALIDATION_OUTLINE_REQUEST = 'GET_VALIDATION_OUTLINE_REQUEST'
export const GET_VALIDATION_OUTLINE_SUCCESS = 'GET_VALIDATION_OUTLINE_SUCCESS'
export const GET_VALIDATION_OUTLINE_FAIL = 'GET_VALIDATION_OUTLINE_FAIL'

export const UPDATE_USER_VALIDATION_REQUEST = 'UPDATE_USER_VALIDATION_REQUEST'
export const UPDATE_USER_VALIDATION_SUCCESS = 'UPDATE_USER_VALIDATION_SUCCESS'
export const UPDATE_USER_VALIDATION_FAIL = 'UPDATE_USER_VALIDATION_FAIL'

export const ON_JURISDICTION_CHANGE = 'ON_JURISDICTION_CHANGE'

export const GET_CODED_USERS_LIST_REQUEST = 'GET_CODED_USERS_LIST_REQUEST'
export const GET_CODED_USERS_LIST_SUCCESS = 'GET_CODED_USERS_LIST_SUCCESS'
export const GET_CODED_USERS_LIST_FAIL = 'GET_CODED_USERS_LIST_FAIL'

export const GET_USER_VALIDATED_QUESTIONS_REQUEST = 'GET_USER_VALIDATED_QUESTIONS_REQUEST'
export const GET_USER_VALIDATED_QUESTIONS_SUCCESS = 'GET_USER_VALIDATED_QUESTIONS_SUCCESS'
export const GET_USER_VALIDATED_QUESTIONS_FAIL = 'GET_USER_VALIDATED_QUESTIONS_FAIL'

export const CLEAR_FLAG = 'CLEAR_FLAG'
export const CLEAR_RED_FLAG = 'CLEAR_RED_FLAG'

export const GET_QUESTION_REQUEST = 'GET_QUESTION_REQUEST'
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS'
export const GET_QUESTION_FAIL = 'GET_QUESTION_FAIL'