export const GET_VALIDATION_OUTLINE_REQUEST = 'GET_VALIDATION_OUTLINE_REQUEST'
export const GET_VALIDATION_OUTLINE_SUCCESS = 'GET_VALIDATION_OUTLINE_SUCCESS'
export const GET_VALIDATION_OUTLINE_FAIL = 'GET_VALIDATION_OUTLINE_FAIL'

export const GET_VALIDATION_NEXT_QUESTION = 'GET_VALIDATION_NEXT_QUESTION'
export const GET_VALIDATION_PREV_QUESTIONS = 'GET_VALIDATION_PREV_QUESTIONS'