/*
  This holds all of the action types that are used by both Coding and Validation
 */
export const UPDATE_USER_ANSWER = 'UPDATE_USER_ANSWER'

export const ON_CHANGE_COMMENT = 'ON_CHANGE_COMMENT'
export const ON_CHANGE_PINCITE = 'ON_CHANGE_PINCITE'
export const ON_APPLY_ANSWER_TO_ALL = 'ON_APPLY_ANSWER_TO_ALL'

export const UPDATE_EDITED_FIELDS = 'UPDATE_EDITED_FIELDS'
export const ON_CLOSE_SCREEN = 'ON_CLOSE_SCREEN'

export const ON_CHANGE_JURISDICTION = 'ON_CHANGE_JURISDICTION'
export const ON_CHANGE_CATEGORY = 'ON_CHANGE_CATEGORY'
export const ON_CLEAR_ANSWER = 'ON_CLEAR_ANSWER'

export const ON_QUESTION_SELECTED_IN_NAV = 'ON_QUESTION_SELECTED_IN_NAV'
export const GET_NEXT_QUESTION = 'GET_NEXT_QUESTION'
export const GET_PREV_QUESTION = 'GET_PREV_QUESTION'
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS'
export const GET_QUESTION_FAIL = 'GET_QUESTION_FAIL'

export const CLEAR_ANSWER_ERROR = 'CLEAR_ANSWER_ERROR'
export const DISMISS_API_ALERT = 'DISMISS_API_ALERT'

export const ON_SHOW_PAGE_LOADER = 'ON_SHOW_PAGE_LOADER'
export const ON_SHOW_QUESTION_LOADER = 'ON_SHOW_QUESTION_LOADER'

export const SAVE_USER_ANSWER_REQUEST = 'SAVE_USER_ANSWER_REQUEST'
export const SAVE_USER_ANSWER_FAIL = 'SAVE_USER_ANSWER_FAIL'
export const SAVE_USER_ANSWER_SUCCESS = 'SAVE_USER_ANSWER_SUCCESS'

export const ADD_REQUEST_TO_QUEUE = 'ADD_REQUEST_TO_QUEUE'
export const REMOVE_REQUEST_FROM_QUEUE = 'REMOVE_REQUEST_FROM_QUEUE'
export const SEND_QUEUE_REQUESTS = 'SEND_QUEUE_REQUESTS'

export const CHANGE_TOUCHED_STATUS = 'CHANGE_TOUCHED_STATUS'