/*
  This holds all of the action types that are used by both Coding and Validation
 */
export const UPDATE_USER_ANSWER_REQUEST = 'UPDATE_USER_ANSWER_REQUEST'
export const ON_CHANGE_COMMENT = 'ON_CHANGE_COMMENT'
export const ON_CHANGE_PINCITE = 'ON_CHANGE_PINCITE'
export const ON_APPLY_ANSWER_TO_ALL = 'ON_APPLY_ANSWER_TO_ALL'

export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS'
export const UPDATE_EDITED_FIELDS = 'UPDATE_EDITED_FIELDS'
export const ON_CLOSE_SCREEN = 'ON_CLOSE_SCREEN'

export const ON_CHANGE_JURISDICTION = 'ON_CHANGE_JURISDICTION'
export const ON_CHANGE_CATEGORY = 'ON_CHANGE_CATEGORY'
export const ON_CLEAR_ANSWER = 'ON_CLEAR_ANSWER'

export const ON_QUESTION_SELECTED_IN_NAV = 'ON_QUESTION_SELECTED_IN_NAV'
export const GET_NEXT_QUESTION = 'GET_NEXT_QUESTION'
export const GET_PREV_QUESTION = 'GET_PREV_QUESTION'
