export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST'
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL'

export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL'

export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST'
export const ADD_PROJECT_FAIL = 'ADD_PROJECT_FAIL'

export const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK'
export const TOGGLE_BOOKMARK_SUCCESS = 'TOGGLE_BOOKMARK_SUCCESS'

export const SORT_PROJECTS = 'SORT_PROJECTS'
export const UPDATE_PAGE = 'UPDATE_PAGE'
export const UPDATE_ROWS = 'UPDATE_ROWS'

export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE'

export const SORT_BOOKMARKED = 'SORT_BOOKMARKED'
