export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST'
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL'
export const GET_PROJECT_USERS_REQUEST = 'GET_PROJECT_USERS_REQUEST'
export const GET_PROJECT_USERS_FAIL = 'GET_PROJECT_USERS_FAIL'
export const GET_PROJECT_USERS_SUCCESS = 'GET_PROJECT_USERS_SUCCESS'

export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL'

export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS'
export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST'
export const ADD_PROJECT_FAIL = 'ADD_PROJECT_FAIL'

export const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK'
export const TOGGLE_BOOKMARK_SUCCESS = 'TOGGLE_BOOKMARK_SUCCESS'

export const SORT_PROJECTS = 'SORT_PROJECTS'
export const UPDATE_PAGE = 'UPDATE_PAGE'
export const UPDATE_ROWS = 'UPDATE_ROWS'

export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE'

export const SORT_BOOKMARKED = 'SORT_BOOKMARKED'

export const FLUSH_STATE = 'FLUSH_STATE'

export const UPDATE_EDITED_FIELDS = 'UPDATE_EDITED_FIELDS'

export const ADD_JURISDICTION_TO_PROJECT = 'ADD_JURISDICTION_TO_PROJECT'
export const UPDATE_JURISDICTION_IN_PROJECT = 'UPDATE_JURISDICTION_IN_PROJECT'
export const ADD_PRESET_JURISDICTION_TO_PROJECT = 'ADD_PRESET_JURISDICTION_TO_PROJECT'
export const DELETE_JURISDICTION_FROM_PROJECT = 'DELETE_JURISDICTION_FROM_PROJECT'

export const RESET_FORM_ERROR = 'RESET_FORM_ERROR'

export const EXPORT_DATA_REQUEST = 'EXPORT_DATA_REQUEST'
export const EXPORT_DATA_SUCCESS = 'EXPORT_DATA_SUCCESS'
export const EXPORT_DATA_FAIL = 'EXPORT_DATA_FAIL'
export const CLEAR_PROJECT_TO_EXPORT = 'CLEAR_PROJECT_TO_EXPORT'
export const DISMISS_API_ERROR = 'DISMISS_API_ERROR'