export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const CHECK_PIV_USER_REQUEST = 'CHECK_PIV_USER_REQUEST'
export const CHECK_PIV_USER_SUCCESS = 'CHECK_PIV_USER_SUCCESS'
export const CHECK_PIV_USER_FAIL = 'CHECK_PIV_USER_FAIL'

export const LOGOUT_USER = 'LOGOUT_USER'
export const FLUSH_STATE = 'FLUSH_STATE'