export const UPDATE_PROTOCOL = 'UPDATE_PROTOCOL'

export const SAVE_PROTOCOL_REQUEST = 'SAVE_PROTOCOL_REQUEST'
export const SAVE_PROTOCOL_SUCCESS = 'SAVE_PROTOCOL_SUCCESS'
export const SAVE_PROTOCOL_FAIL = 'SAVE_PROTOCOL_FAIL'

export const GET_PROTOCOL_REQUEST = 'GET_PROTOCOL_REQUEST'
export const GET_PROTOCOL_SUCCESS = 'GET_PROTOCOL_SUCCESS'
export const GET_PROTOCOL_FAIL = 'GET_PROTOCOL_FAIL'

export const LOCK_PROTOCOL_REQUEST = 'LOCK_PROTOCOL_REQUEST'
export const LOCK_PROTOCOL_SUCCESS = 'LOCK_PROTOCOL_SUCCESS'
export const LOCK_PROTOCOL_FAIL = 'LOCK_PROTOCOL_FAIL'

export const UNLOCK_PROTOCOL_REQUEST = 'UNLOCK_PROTOCOL_REQUEST'
export const UNLOCK_PROTOCOL_SUCCESS = 'UNLOCK_PROTOCOL_SUCCESS'
export const UNLOCK_PROTOCOL_FAIL = 'UNLOCK_PROTOCOL_FAIL'

export const UPDATE_EDITED_FIELDS = 'UPDATE_EDITED_FIELDS'
export const RESET_LOCK_ALERT_PROTOCOL = 'RESET_LOCK_ALERT_PROTOCOL'
export const RESET_ALERT_ERROR = 'RESET_ALERT_ERROR'
export const CLEAR_STATE = 'CLEAR_STATE'