export const UPDATE_PROTOCOL = 'UPDATE_PROTOCOL'
export const SAVE_PROTOCOL_REQUEST = 'SAVE_PROTOCOL_REQUEST'
export const SAVE_PROTOCOL_SUCCESS = 'SAVE_PROTOCOL_SUCCESS'
export const SAVE_PROTOCOL_FAIL = 'SAVE_PROTOCOL_FAIL'