export const UPDATE_PROTOCOL = 'UPDATE_PROTOCOL'

export const SAVE_PROTOCOL_REQUEST = 'SAVE_PROTOCOL_REQUEST'
export const SAVE_PROTOCOL_SUCCESS = 'SAVE_PROTOCOL_SUCCESS'
export const SAVE_PROTOCOL_FAIL = 'SAVE_PROTOCOL_FAIL'

export const GET_PROTOCOL_REQUEST = 'GET_PROTOCOL_REQUEST'
export const GET_PROTOCOL_SUCCESS = 'GET_PROTOCOL_SUCCESS'
export const GET_PROTOCOL_FAIL = 'GET_PROTOCOL_FAIL'

export const UPDATE_EDITED_FIELDS = 'UPDATE_EDITED_FIELDS'

export const RESET_SAVE_ERROR = 'RESET_SAVE_ERROR'
export const CLEAR_STATE = 'CLEAR_STATE'